//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication10.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Chitiethanhtoan
    {
        public string Mã_ĐH { get; set; }
        public int Mã_HTTT { get; set; }
        public int Số_tiền { get; set; }
    
        public virtual Donhang Donhang { get; set; }
        public virtual Hinhthucthanhtoan Hinhthucthanhtoan { get; set; }
    }
}
