//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication10.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Giohang
    {
        public Giohang()
        {
            this.Chitietgiohangs = new HashSet<Chitietgiohang>();
        }
    
        public string Mã_GH { get; set; }
        public string Email { get; set; }
        public int Tổng_tiền { get; set; }
        public System.DateTime Ngày_tạo { get; set; }
    
        public virtual ICollection<Chitietgiohang> Chitietgiohangs { get; set; }
        public virtual Khachhang Khachhang { get; set; }
    }
}
