//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication10.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Hinhthucthanhtoan
    {
        public Hinhthucthanhtoan()
        {
            this.Chitiethanhtoans = new HashSet<Chitiethanhtoan>();
        }
    
        public int Mã_HTTT { get; set; }
        public string Hình_thức_thanh_toán { get; set; }
    
        public virtual ICollection<Chitiethanhtoan> Chitiethanhtoans { get; set; }
    }
}
