//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication10.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Khachhang
    {
        public Khachhang()
        {
            this.Donhangs = new HashSet<Donhang>();
            this.Giohangs = new HashSet<Giohang>();
        }
    
        public string Email { get; set; }
        public string Họ_tên { get; set; }
        public string SĐT { get; set; }
        public string Địa_chỉ { get; set; }
    
        public virtual ICollection<Donhang> Donhangs { get; set; }
        public virtual ICollection<Giohang> Giohangs { get; set; }
    }
}
