//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication10.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Loaisanpham
    {
        public Loaisanpham()
        {
            this.Sanphams = new HashSet<Sanpham>();
        }
    
        public string Mã_loại_SP { get; set; }
        public string Tên_loại_SP { get; set; }
    
        public virtual ICollection<Sanpham> Sanphams { get; set; }
    }
}
