//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication10.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Trangthaidonhang
    {
        public Trangthaidonhang()
        {
            this.Donhangs = new HashSet<Donhang>();
        }
    
        public int Mã_TT { get; set; }
        public string Trạng_thái { get; set; }
    
        public virtual ICollection<Donhang> Donhangs { get; set; }
    }
}
